apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-upgrade-demo
  region: $AWS_REGION
  version: "$K8S_CURRENT_VERSION"

iam:
  withOIDC: true

vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single

# Node Groups for cluster add-ons
managedNodeGroups:
  - name: managed-node-add-ons
    instanceType: m5.large
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    volumeSize: 30
    updateConfig:
      maxUnavailable: 1 # or `maxUnavailablePercentage: 75` to specify maxUnavailable as a percentage of total nodes
    ssh:
      allow: false
      enableSsm: true
      publicKeyPath: ""
    labels: {role: add-ons}
    privateNetworking: true
    # Note: unmanaged nodegroups (`nodeGroups` field) use a different structure (map[string]string) to express taints
    # taints:
    # - key: key1
    #   value: value1
    #   effect: NoSchedule
    tags:
      Name: managed-node-add-ons
      nodegroup-role: worker

addons:
  - name: vpc-cni # no version is specified so it deploys the default version
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest

gitops:
  flux:
    gitProvider: github             # required. options are github or gitlab
    flags:                          # required. arbitrary map[string]string for all flux args.
    # these args are not controlled by eksctl. see https://fluxcd.io/docs/get-started/ for all available flags
      owner: "$GITHUB_USER"
      repository: "eks-cluster-upgrades-reference-arch"
      private: "true"
      branch: "main"
      namespace: "flux-system"
      path: "gitops/clusters/cluster-demo"

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
